### ISSUE TITLE
symbols-outline.lua:307: attempt to index field 'vijw' (a nil value)

### ISSUE THREAD

**Issue by zhanglin2018** [simrat39/symbols-outline.nvim#156]
![image](https://user-images.githubusercontent.com/35573227/185741670-a25060fc-a29e-4f37-8d58-53b926b317e9.png)

E5108: Error executing lua ...acker/start/symbols-outline.nvim/lua/symbols-outline.lua:307: attempt to index field 'vijw' (a nil value)
stack traceback:
        ...acker/start/symbols-outline.nvim/lua/symbols-outline.lua:307: in function 'toggle_outline'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue

**Comment by zhanglin2018** [comment]
i don't know how to fix this issue.

**Comment by smartding** [comment]
I've a similar error whenever I run the `SymbolsOutlineOpen` command

```lua
E5108: Error executing lua ...acker/start/symbols-outline.nvim/lua/symbols-outline.lua:315: attempt to index field 'view' (a nil value)
stack traceback:
        ...acker/start/symbols-outline.nvim/lua/symbols-outline.lua:315: in function 'open_outline'
        [string ":lua"]:1: in main chunk
```

**Comment by Geraint** [comment]
I suspect the configuration pattern may have changed recently.

I was getting a very similar error message.

My error message said `attempt to index field 'view' (a nil value)` - note `view` rather than `vijw` (I suspect a typo in your bug report, @zhanglin2018 ...?).

My config contained a line that looked like this:

```lua
vim.g.symbols_outline = { ... }
```

Rather than setting that global variable, I have changed it so I pass the table directly to the `setup()` method, and the problem has gone away:

```lua
require("symbols-outline").setup({ ... })
```

**Comment by brt** [comment]
@Geraint i'm not the original poster but thank you very much for your input here! I was very much puzzled with the very same issue and kept checking here for a fix... and it worked exactly as you describe.

**Comment by dzintars** [comment]
Went there before I found that I had `local ok, outline = pcall(require, "symbols_outline")` at my config. Should be `symbols-outline`.
