### ISSUE TITLE
Layout seems broken with python-lsp-server and python-language-server

### ISSUE THREAD

**Issue by duikboot** [simrat39/symbols-outline.nvim#17]
Hi,

I installed the python-lsp-server, which works very nice with symbols-outline.nvim. But is seems the layout is broken.
The config works with jedi-language-server.

My config:

require('symbols-outline')

```
vim.g.symbols_outline = {
    highlight_hovered_item = true,
    show_guides = true,
    auto_preview = false, -- experimental
    position = 'right',
    keymaps = {
        close = "<Esc>",
        goto_location = "<Cr>",
        focus_location = "o",
        hover_symbol = "<C-space>",
        rename_symbol = "r",
        code_actions = "a",
    },
    lsp_blacklist = {},
}
```

![2021-05-07-211714](https://user-images.githubusercontent.com/240139/117498276-e272a580-af79-11eb-92c1-c8b1bb8e8865.png)

Arjen

**Comment by simrat39** [comment]
If by broken layout you mean that the symbols inside the function dont actually show up inside the function, this is because pyls does not support a hierarchical view of the symbols. I would say use pyright because that does support it, and if you want to use both of these language servers together then add pyls to the blacklist
