### ISSUE TITLE
Doesn't work with pyls (python-language-server)

### ISSUE THREAD

**Issue by duikboot** [simrat39/symbols-outline.nvim#5]
Hi,

Love your plugin. It doesn't work for python-language-server, it fails with the following error.

`Error executing vim.schedule lua callback: ...gged/symbols-outline.nvim/lua/symbols-outline/parser.lua:42: attempt to index field 'selectionRange' (a nil value)`

Weirdly, it does work for jedi-language-server (another python language server), so I'm not sure if I should report the error here or somewhere else.

**Comment by simrat39** [comment]
From the LSP spec:

Document Symbols Request (:leftwards_arrow_with_hook:)
The document symbol request is sent from the client to the server. The returned result is either

SymbolInformation[] which is a flat list of all symbols found in a given text document. Then neither the symbol’s location range nor the symbol’s container name should be used to infer a hierarchy.
DocumentSymbol[] which is a hierarchy of symbols found in a given text document.
Servers should whenever possible return DocumentSymbol since it is the richer data structure.

( I THINK THIS IS WHATS HAPPENING BUT I HAVENT LOOKED AT IT PROPERLY)
You can probably guess what's happening. I should add a check for SymbolInformation[]  and then handle it, but that severely handicaps the plugins capabilities. Anyways, I'm pretty sure pyright is now used over pyls ( I think ), both by microsoft

**Comment by duikboot** [comment]
Thanks a lot for your time. I'll try pyright for now. Thanks. Should I keep this issue open?

**Comment by simrat39** [comment]
@duikboot close it if it works with pyright

**Comment by simrat39** [comment]
Tested with pyright, seems to work

**Comment by duikboot** [comment]
Thanks a lot!
